spring.datasource.url=jdbc:mysql://localhost:3306/nutribalance
spring.datasource.username=root
spring.datasource.password=1510

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
